export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_START = 'AUTH_START';

export const AUTH_RESTORE_SESSION = 'AUTH_RESTORE_SESSION';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';

// export const SEND_START = 'SEND_START';
// export const SEND_SUCCESS = 'SEND_SUCCESS';
// export const SET_CURRENT_RESPONSE = 'SET_CURRENT_RESPONSE';
// export const CLEAR_HISTORY = 'CLEAR_HISTORY';
// export const UPDATE_RESPONSE_DATA = 'UPDATE_RESPONSE_DATA';